spring.application.name=servdvadva
spring.datasource.url = jdbc:postgresql://localhost:5432/rewuoge
spring.datasource.username = postgres
spring.datasource.password = 123
spring.jpa.properties.hibernate.dialect =  org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update